### 实现 Validator 接口
GET localhost:8888/context/validator/validation
Content-Type: application/json

{
  "id": "123",
  "name": "asd"
}
### 使用注解
GET localhost:8888/context/validator/valid
Content-Type: application/json

{
  "id": "123",
  "name": ""
}