server:
  port: 8888

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.173.100:3306
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
